# Generated by Django 4.2.16 on 2026-04-12 13:02

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL slug, e.g. data-analytics-course-online', max_length=120, unique=True)),
                ('niche', models.CharField(choices=[('data-analytics', 'Data Analytics'), ('data-science', 'Data Science'), ('generative-ai', 'Generative AI')], max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline shown below the title', max_length=200)),
                ('description', models.TextField(help_text='Full course description (1500+ words capacity)')),
                ('curriculum', models.JSONField(default=list, help_text='Array of topics or module objects (JSON)')),
                ('salary_insights', models.TextField(blank=True, help_text='Salary range, job outlook, and career information')),
                ('hero_banner', models.ImageField(blank=True, help_text='Hero banner image (recommended: 1200×630px)', null=True, upload_to=courses.models.course_banner_path)),
                ('hero_banner_alt', models.CharField(blank=True, help_text='Alt text for the hero banner (SEO & accessibility)', max_length=200)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=12)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('beginner-to-advanced', 'Beginner to Advanced')], default='beginner-to-advanced', max_length=25)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Course price in INR (null = contact for pricing)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-is_featured', 'niche', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='PNG/SVG icon shown on the course page', null=True, upload_to=courses.models.tool_icon_path)),
                ('alt_text', models.CharField(help_text='Alt text for the tool icon image (SEO & accessibility)', max_length=200)),
                ('website_url', models.URLField(blank=True, help_text='Official tool website (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='<title> tag — keep under 60 characters for best display', max_length=70)),
                ('meta_description', models.CharField(help_text='Meta description — keep 120–155 characters', max_length=160)),
                ('og_title', models.CharField(blank=True, max_length=70)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200×630px)', null=True, upload_to=courses.models.seo_og_image_path)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL — leave blank to auto-generate from slug')),
                ('faq_schema', models.JSONField(default=list, help_text='FAQ pairs — injected as JSON-LD FAQPage schema by the frontend')),
                ('schema_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for Course schema markup', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='courses.course')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='Tools / technologies taught in this course', related_name='courses', to='courses.tool'),
        ),
    ]
