# Generated by Django 4.2.16 on 2026-04-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="niche",
            field=models.CharField(
                choices=[
                    ("data-analytics", "Data Analytics"),
                    ("data-science", "Data Science"),
                    ("generative-ai", "Generative AI"),
                    ("azure-data-engineering", "Azure Data Engineering"),
                ],
                max_length=50,
            ),
        ),
    ]
