# Generated by Django 4.2.16 on 2026-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_niche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="niche",
            field=models.CharField(
                help_text="e.g. data-analytics, data-science, generative-ai, azure-data-engineering",
                max_length=100,
            ),
        ),
    ]
